[package]
name = "legion"
version = "1.0.0"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
rayon = "1.5.3"
owo-colors = "3.4.0"
snowflake = "1.3.0"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.tokio]
version = "1.19.2"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.14"
features = ["env-filter"]

[dependencies.moka]
version = "0.9.0"
features = ["future", "dash"]

[dependencies.config]
version = "0.13.1"
features = ["toml", "yaml"]
